### ISSUE TITLE
Crash on start "Failed to find storage device"

### ISSUE THREAD

**Issue by sarg** [shanemd/PodListen#20]
I'm using Xiaomi Redmi 7A and app fails to start for me. On Oneplus One it works fine.

```
java.lang.IllegalArgumentException: Failed to find storage device at /data/data/com.einmalfel.podlisten.debug/files
01-29 22:41:48.651 25465 25465 E STR     :      at android.os.Environment.isExternalStorageRemovable(Environment.java:955)
01-29 22:41:48.651 25465 25465 E STR     :      at com.einmalfel.podlisten.Storage.isRemovable(Storage.java:260)
01-29 22:41:48.651 25465 25465 E STR     :      at com.einmalfel.podlisten.Preferences.readPreference(Preferences.java:399)
01-29 22:41:48.651 25465 25465 E STR     :      at com.einmalfel.podlisten.Preferences.<init>(Preferences.java:261)
01-29 22:41:48.651 25465 25465 E STR     :      at com.einmalfel.podlisten.Preferences.getInstance(Preferences.java:269)
```

**Comment by shanemd** [comment]
Hi @sarg. Thanks for opening an issue. :)

I ran into the same problem when I was first getting this project building. Are you deploying via Android Studio or directly using the gradlew command? This only happens for me when using Android Studio.

**Comment by shanemd** [comment]
For reference:

This worked for me:
`PodListen$ ./gradlew installDebug`

You might have to run this first, but I'm not sure. Perhaps the installDebug tasks includes assembleDebug.
`PodListen$ ./gradlew assembleDebug`

**Comment by shanemd** [comment]
Also, I'll take a look at your PR, just noticed that.

**Comment by sarg** [comment]
I'm using `./gradlew packageDebug` and `adb install`
